server:
  port: 8080
github:
  client:
    id: 46877742177b45e76d62
    secret: fea8fd98fdfcdfa8fe6df9d1b1f01f702dfcccee
  redirect:
    url: http://localhost:8080/callback
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    typeAliasesPackage: com.example.study.mapper
#    mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    url : jdbc:h2:~/test
    username : sa
#    password : 123456
    driver-class-name: org.h2.Driver

#management:
#  server:
#    port : 8081
#  endpoints:
#      web:
#        exposure:
#          include: "*"

